### KERAS: load - save weights ###

This notebook demonstrates, how to save model, save ALL weights and save weights for one layer
In the last case it demonstrates, how to load 1 - layer weights

In [1]:
import tensorflow
tensorflow.__version__

'1.15.0'

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os, sys, time, json, subprocess
import cv2

#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import skimage.io
from tensorflow.python.keras.applications import ResNet50
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, GlobalAveragePooling2D
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions



In [4]:
from tensorflow.keras.models import model_from_json, load_model

In [5]:
from panda_bvv_config import *

In [6]:
def prepare_test_data(test_arr):
    test_data = []
    images_names = []
    for test_name in test_arr:        
        image_id = test_name.split('.')[0]        
        test_file = os.path.join(train_size2, test_name)
        biopsy = skimage.io.MultiImage(test_file)
        out_file = cv2.resize(biopsy[-1], (512, 512))
        test_data.append(out_file)
        images_names.append(image_id)
        #print(time.time())
        del biopsy
    return np.array(images_names), np.array(test_data)

In [7]:
#model1 = load_model('../input/panda-model-1/panda_very_simple_net_based_on_resnet50.h5')
model1 = load_model('panda_very_simple_net_based_on_resnet50.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [9]:
model1.save_weights('ww1', save_format="h5")

In [13]:
model1.layers

In [14]:
json_config = model1.to_json()

In [9]:
with open('resnet.json', 'w') as f:
    json.dump(json_config, f)

In [18]:
weightsAndBiases = model1.layers[1].get_weights()

In [22]:
len(weightsAndBiases)

2

In [21]:
len(weightsAndBiases[0])

2048

In [23]:
len(weightsAndBiases[1])

6

In [24]:
weightsAndBiases[1]

array([0.02726565, 0.0180606 , 0.02624424, 0.03013413, 0.02131156,
       0.01192806], dtype=float32)

In [25]:
np.save('panda1_weights', weightsAndBiases[0])
np.save('panda1_biases', weightsAndBiases[1])

In [28]:
panda1_weights = np.load('panda1_weights.npy')
panda1_biases = np.load('panda1_biases.npy')

In [10]:
resn = ResNet50(include_top=False, pooling='avg', weights='imagenet')

In [18]:
resn.save_weights('resnet_weights.h5')

In [22]:
weights = resn.get_weights()

In [23]:
len(weights)

318

In [8]:
json_config = resn.to_json()

In [25]:
os.getcwd()

'/home/admin/pca'

In [7]:
with open('resnet.json') as jsonfile:
    resnet = json.load(jsonfile)

In [8]:
model2 = model_from_json(resnet)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [22]:
weights = model2.layers[30].get_weights()
weights

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1

In [23]:
model2.load_weights('resnet_weights.h5')

In [24]:
weights = model2.layers[30].get_weights()
weights

[array([1.3269103 , 1.2560703 , 0.9950278 , 0.8948056 , 1.2032318 ,
        0.9346237 , 1.0054843 , 1.0860608 , 0.6295145 , 0.6699675 ,
        1.159417  , 0.72101206, 0.92272604, 1.0163767 , 0.92679834,
        1.0108758 , 1.0348027 , 0.77844113, 0.9101868 , 0.8505309 ,
        0.630787  , 0.85698867, 0.5740686 , 0.92753345, 1.1684022 ,
        1.296549  , 0.7672808 , 0.6602154 , 0.6786608 , 1.0906765 ,
        0.734093  , 1.1532717 , 1.424539  , 0.7793672 , 1.4337783 ,
        0.7280245 , 1.5290251 , 1.3166497 , 0.9573881 , 1.6880441 ,
        1.1068428 , 1.0061102 , 1.013545  , 1.2786397 , 1.231336  ,
        1.1585219 , 0.9538531 , 0.9335715 , 1.202661  , 1.2151445 ,
        1.3699788 , 1.3164968 , 0.896061  , 1.1104871 , 1.3098865 ,
        1.2052519 , 0.71763515, 0.9407204 , 0.9892499 , 0.71910447,
        1.3878453 , 0.98184586, 1.1043916 , 1.2413356 ], dtype=float32),
 array([-1.177437  , -1.0913068 , -0.161753  ,  0.13188034, -0.6317326 ,
         0.43973786,  0.153783  , -0.9

In [33]:
vars(model2.layers[2])

{'_self_setattr_tracking': True,
 '_trainable': True,
 'stateful': False,
 '_input_spec': InputSpec(ndim=4, axes={-1: 3}),
 'supports_masking': False,
 '_name': 'conv1_conv',
 '_activity_regularizer': None,
 '_trainable_weights': [<tf.Variable 'conv1_conv/kernel:0' shape=(7, 7, 3, 64) dtype=float32>,
  <tf.Variable 'conv1_conv/bias:0' shape=(64,) dtype=float32>],
 '_non_trainable_weights': [],
 '_updates': [],
 '_thread_local': <_thread._local at 0x7f19333bd938>,
 '_callable_losses': [],
 '_losses': [],
 '_metrics': [],
 '_dtype_policy': <Policy "float32", loss_scale=None>,
 '_dtype_defaulted_to_floatx': False,
 '_autocast': False,
 '_layers': [],
 '_inbound_nodes': [<tensorflow.python.keras.engine.node.Node at 0x7f19338a5550>],
 '_outbound_nodes': [<tensorflow.python.keras.engine.node.Node at 0x7f19338b3b00>],
 '_expects_training_arg': False,
 '_expects_mask_arg': False,
 '_dynamic': False,
 '_initial_weights': None,
 '_obj_reference_counts_dict': ObjectIdentityDictionary({<_ObjectIde

In [32]:
model1_col = Sequential()

model1_col.add(resn)
model1_col.add(Dense(6, activation='softmax'))

model1_col.layers[1].set_weights([panda1_weights,panda1_biases ])




In [47]:
model1_col.layers[0].summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, None, None, 3 0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, None, None, 6 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, None, None, 6 256         conv1_conv[0][0]                 
___________________________________________________________________________________________

In [9]:
test_files = os.listdir(train_size2)[:10]

In [10]:
%time test_files_id_array,  test_file_data_array = prepare_test_data(test_files)

CPU times: user 330 ms, sys: 51.4 ms, total: 381 ms
Wall time: 346 ms


In [42]:
np.testing.assert_allclose(
  model1.predict(test_file_data_array),
  model1_col.predict(test_file_data_array))

In [11]:
model2.predict(test_file_data_array)

array([[ 0.41003644, 29.211624  ,  0.09817909, ..., 21.11559   ,
         7.7985168 , 17.948622  ],
       [ 0.46023583, 28.99054   ,  0.09250913, ..., 21.155151  ,
         7.5596924 , 17.781845  ],
       [ 0.5986584 , 28.122675  ,  0.09456299, ..., 20.841658  ,
         6.9981527 , 17.357159  ],
       ...,
       [ 0.47411382, 28.765768  ,  0.09387199, ..., 21.123575  ,
         7.592279  , 17.690485  ],
       [ 0.4819616 , 27.437103  ,  0.09101237, ..., 20.350737  ,
         6.8262753 , 17.088312  ],
       [ 0.4239514 , 29.039246  ,  0.09058451, ..., 21.115335  ,
         7.6210456 , 17.850855  ]], dtype=float32)

In [43]:
model1.predict(test_file_data_array)

array([[0.28821334, 0.38486978, 0.23148952, 0.04876641, 0.02068294,
        0.02597807],
       [0.47480458, 0.22281939, 0.24892458, 0.01614753, 0.01314074,
        0.02416308],
       [0.05701469, 0.22335555, 0.5694882 , 0.01342048, 0.00798638,
        0.12873472],
       [0.17873767, 0.11959693, 0.31902948, 0.01772925, 0.2988086 ,
        0.06609808],
       [0.06730898, 0.31158283, 0.48209006, 0.01111331, 0.02677212,
        0.10113274],
       [0.17865075, 0.1720339 , 0.28404307, 0.00426394, 0.11284523,
        0.24816307],
       [0.33716965, 0.278547  , 0.2909285 , 0.01402659, 0.02988067,
        0.04944761],
       [0.06607961, 0.18532537, 0.6996822 , 0.01705234, 0.01513504,
        0.01672544],
       [0.16628884, 0.168219  , 0.47756848, 0.01561058, 0.12151735,
        0.05079573],
       [0.3887904 , 0.41253272, 0.14184919, 0.01253888, 0.01623292,
        0.02805601]], dtype=float32)

In [44]:
model1_col.predict(test_file_data_array)

array([[0.28821334, 0.38486978, 0.23148952, 0.04876641, 0.02068294,
        0.02597807],
       [0.47480458, 0.22281939, 0.24892458, 0.01614753, 0.01314074,
        0.02416308],
       [0.05701469, 0.22335555, 0.5694882 , 0.01342048, 0.00798638,
        0.12873472],
       [0.17873767, 0.11959693, 0.31902948, 0.01772925, 0.2988086 ,
        0.06609808],
       [0.06730898, 0.31158283, 0.48209006, 0.01111331, 0.02677212,
        0.10113274],
       [0.17865075, 0.1720339 , 0.28404307, 0.00426394, 0.11284523,
        0.24816307],
       [0.33716965, 0.278547  , 0.2909285 , 0.01402659, 0.02988067,
        0.04944761],
       [0.06607961, 0.18532537, 0.6996822 , 0.01705234, 0.01513504,
        0.01672544],
       [0.16628884, 0.168219  , 0.47756848, 0.01561058, 0.12151735,
        0.05079573],
       [0.3887904 , 0.41253272, 0.14184919, 0.01253888, 0.01623292,
        0.02805601]], dtype=float32)

In [ ]:
def make_submission_df(id_array, test_labels):
    #assert len(id_array) == len(test_labels), "different length for label arrays"
    #assert isinstance(id_array, np.ndarray), 'images id is not a numpy array'
    #assert isinstance(test_labels, np.ndarray), 'test labels array is not a numpy array'
    d2 = {'image_id': id_array, 'isup_grade': test_labels}
    new_sample = pd.DataFrame(data=d2)
    #final_sample = pd.concat([sample_df, new_sample], ignore_index=True)
    return new_sample #final_sample

In [ ]:
#test_files = os.listdir(from_fold)[:10]
#test_files

In [ ]:
#biopsy = skimage.io.MultiImage(os.path.join(from_fold,'0cc35bc0fe4dd912b20f72d66888fd49.tiff'))

In [ ]:
#biopsy[-1].shape

In [ ]:
if os.path.exists(from_fold):
    test_files = os.listdir(from_fold) #[:100]
    %time test_files_id_array,  test_file_data_array = prepare_test_data(test_files)
    print(test_files_id_array.shape)
    print(test_file_data_array.shape)
    %time pred_all = model1.predict(test_file_data_array)
    final_test_labels = pred_all.argmax(axis=-1)
    submission = make_submission_df(test_files_id_array, final_test_labels)
    submission['isup_grade'] = submission['isup_grade'].astype(int)
    submission.head()
    submission.to_csv('submission.csv', index=False)
else:
    sub = pd.read_csv("/kaggle/input/prostate-cancer-grade-assessment/sample_submission.csv")
    sub.to_csv('submission.csv', index=False)
    print('no submission data')